Don't clean up RGs that are owned by something. (#1527)
* Tolerate an RG getting deleted while the script is running

Otherwise this happens:

Traceback (most recent call last):
  File "src/resources_cleanup.py", line 164, in <module>
    main()
  File "src/resources_cleanup.py", line 159, in main
    process_resource_groups_of_subscription(subscription_id, resource_client)
  File "src/resources_cleanup.py", line 86, in process_resource_groups_of_subscription
    process_resource_group(resource_group, resource_client)
  File "src/resources_cleanup.py", line 93, in process_resource_group
    resource_list = list(
  File "/home/mmazur/.conda/envs/resources-cleaner/lib/python3.8/site-packages/azure/core/paging.py", line 123, in __next__
    return next(self._page_iterator)
  File "/home/mmazur/.conda/envs/resources-cleaner/lib/python3.8/site-packages/azure/core/paging.py", line 75, in __next__
    self._response = self._get_next(self.continuation_token)
  File "/home/mmazur/.conda/envs/resources-cleaner/lib/python3.8/site-packages/azure/mgmt/resource/resources/v2022_09_01/operations/_operations.py", line 9274, in get_next
    map_error(status_code=response.status_code, response=response, error_map=error_map)
  File "/home/mmazur/.conda/envs/resources-cleaner/lib/python3.8/site-packages/azure/core/exceptions.py", line 164, in map_error
    raise error
azure.core.exceptions.ResourceNotFoundError: (ResourceGroupNotFound) Resource group 'e2e_tests_mrg_namegztqp' could not be found.
Code: ResourceGroupNotFound
Message: Resource group 'e2e_tests_mrg_namegztqp' could not be found.

* Only list resources in RG when in Verbose

Script runs in 2 seconds without this, since we're skipping all these
api calls.

* Don't delete RGs that are managed by something

* Add test